version: '3'

services:
  app:
    build: .
    image: flashwise
    ports:
      - 8080:8080
      - 3306:3306
    depends_on:
      - database
    networks:
      - main_network

  database:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: flashwise
    ports:
      - 3306:3306
    volumes:
      - /data:/var/lib/mysql
    networks:
      - main_network

networks:
  main_network:
    name: "flashwise-network"
