version: '3'

services:
  app:
    build: .
    # image: flashwise
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: flashwise

  database:
    image: mysql:8.1
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flashwise

volumes:
  mysql-data:
