#!/usr/bin/env bash
set -euo pipefail

echo "Creating user"

token="$(http POST localhost:8080/api/register \
    username="IntegrationTester" \
    email="integration.tester@gmail.com" \
    password1="tiger123" \
    password2="tiger123" | jq --raw-output '.token')"

echo "Creating flashcard set"

flashcard_set_id="$(http POST localhost:8080/api/sets \
    "Authorization: Token $token" \
    name='Geography' \
    is_public:=true \
    category:=1 | jq --raw-output '.id')"

echo "Adding flashcard 1"

http POST localhost:8080/api/flashcards \
    "Authorization: Token $token" \
    flashcard_set:="$flashcard_set_id" \
    front="Capital of the United States" \
    back="Washington, D.C."

echo "Adding flashcard 2"

http POST localhost:8080/api/flashcards \
    "Authorization: Token $token" \
    flashcard_set:="$flashcard_set_id" \
    front="Capital of France" \
    back="Paris"

echo "Adding flashcard 3"

http POST localhost:8080/api/flashcards \
    "Authorization: Token $token" \
    flashcard_set:="$flashcard_set_id" \
    front="Capital of Japan" \
    back="Tokyo"

echo "Adding flashcard 4"

http POST localhost:8080/api/flashcards \
    "Authorization: Token $token" \
    flashcard_set:="$flashcard_set_id" \
    front="Capital of Brazil" \
    back="Brasília"

echo "Listing flashcards in the set"

http GET localhost:8080/api/flashcards \
	"Authorization: Token $token" \
	set_id=="$flashcard_set_id"
